### ISSUE TITLE
i can't install addon mcblender latest version

### ISSUE THREAD

**Issue by LemonCraft-11** [Nusiq/mcblend#101]
![image](https://user-images.githubusercontent.com/74866868/168454910-6b5dad82-9ba5-4bb8-85e9-f75208135d24.png)

**Comment by Nusiq** [comment]
That's not really a bug. I try to maintain Mcblend to support the most recent LTS version which is currently 2.93. I've seen some people asking about it on Discord so maybe it was a bad decision. The developlment of Mcblend is currently very slow because I work on other open source project in my free time currently (Bedrock-OSS/regolith).
