### ISSUE TITLE
Add a option to change which axis is up

### ISSUE THREAD

**Issue by sekretboi** [Nusiq/mcblend#92]
I use Blender and Blockbench together to make models and animations for Minecraft. However, I noticed that Blender's up axis is set to Z and Blockbench's up axis is set to Y. This make's it hard to add animations to Minecraft through blender since the up axis is set to Y. This can simple be switch by adding an option to change the Up axis when exporting.

**Comment by Nusiq** [comment]
I'm not sure If I understand your problem. Can you describe the process your going through and give an example of unexpected result? If we ignore the names of the axis for a moment, you can identify the orientation of the model by using the orthographic perspective views (numpad keys). For example: when you create a model of a person and add an animation to it to move forward, backwards, left and right. The exported animation should look the same in Minecraft and in Blockbench.

I made this simple example. Maybe it will help with the discussion. I created the model in blender and named the cubes after their locations (using the coordinates system from blender). "x2" cube = 2m at X axis; "y2" cube = 2m at Y axis; "z2" cube = 2m at Z axis.
![image](https://user-images.githubusercontent.com/34062025/125196364-fc6e8400-e259-11eb-8227-1d4097928f4a.png)

And here is the result file (I've hidden the cubes property).
![image](https://user-images.githubusercontent.com/34062025/125196555-abab5b00-e25a-11eb-81c3-663cdf33b71c.png)
_Side note: One interesting thing that you can read from that is that the Blockbench inverts the value of X in comparison to exported model file._

The zip file with exported model (it's in ZIP because Github don't let you upload JSON files in messages):
[my_model.geo.zip](https://github.com/Nusiq/mcblend/files/6796967/my_model.geo.zip)

**Comment by sekretboi** [comment]
Hey, thanks for responding, and an example of my problem is, whenever I export an animation (using bones) it will switch the values of the axis or not include them at all
Here's one of my recent models on blender vs when converted to Blockbench.

https://user-images.githubusercontent.com/39351078/125206225-12794600-e254-11eb-9f2e-3d6e6540f9da.mp4

https://user-images.githubusercontent.com/39351078/125206227-14430980-e254-11eb-936a-8dc295ffe080.mp4

It's moving side to side rather than up and down and arms aren't out. I fear that this might be a different problem entirely but I'm hoping this is nothing to big. Thank you again

**Comment by Nusiq** [comment]
Interesting. I've never seen something like that.
1. What version of Mcblend are you using?
2. Did you use graph editor to smooth this animation? Currently the interpolation between frames in Mcblend is always linear.
3. Could you send me the model. You can contact me via email `nusiq@outlook.com` or you can find me on [Bedrock OSS](https://discord.gg/XjV87YN) discord.

**Comment by Nusiq** [comment]
4. Did you select all of the parts of the entity while exporting the animation?

**Comment by sekretboi** [comment]
Yes, I will send the model and project right away. I am updated to the latest version, 8.0.0, no, I did not use a graph and yes the frames are linear.

**Comment by Nusiq** [comment]
I'm sorry to say that I found multiple problems in the model that you've sent. I'm actually surprised that you were able to export the model with the cubes. I tried to do that with your project but Mcblend didn't export anything except the bones (which is expected for this model but I'll explain that later). It makes me wonder if you accidentally sent a different version of the .blend than the one that was used to export the .geo.json file also attached to the e-mail, if yes, then maybe it's possible to slightly modify the model so it will be exportable.

# The problems:
## Blender Version
When I opened the file I had a message that it was created with newer version of Blender (2.9). Mcblend is developed and tested on 2.83. I doubt that this matters but I think it's worth to mention that. On a side note I noticed that 2.93 LTS has been released so I'll probably move to that version in the future.
## Wrong parent type
You used different type of parenting than Mcblend expects. **This is probably the biggest problem in this project.** Mcblend expects "Parent Type: Bone" but you used "Parent Type: Object" and mesh deformations. I did a bad job in explaining that in user manual and it will definitely get its section there.
![image](https://user-images.githubusercontent.com/34062025/125525496-0b925f9a-7fe9-422d-b05c-7c448d5c2063.png)
I know it's less usual to parent objects to bones than the method that you used so here is a quick tutorial how to do it:
![image](https://user-images.githubusercontent.com/34062025/125527637-a6649a19-57c2-463e-8faf-f7ff6c0cf95d.png)

The fact that you used different parenting type and somehow managed to export the cubes is what surprised me. It shouldn't be possible because with this type of parenting Mcblend only knows that the MESH is parented to ARMATURE. Mcblend doesn't use armatures for anything (it uses the bones of the armature but not the armature itself). At some point of the execution of the exporter code Mcblend checks the parents of all objects (meshes, bones and empties) and sees that the cube is parented to an armature, but since the armature is not a valid part of a model Mcblend also ignores the cube (or at least it should).

In my case everything worked as expected and the cubes weren't exported, but you've send me an exported geometry file. That's why I think that the version of the blend file I've got from you might be different then the one that you used to export the model.

Since the parenting type that you used doesn't actually moves the mesh objects (it moves the vertices instead), you can see what Mcblend sees when it performs the exporting in the edit mode, because it disables all of the vertex transformations:
![image](https://user-images.githubusercontent.com/34062025/125530520-2d3d2384-0e59-4080-b3e2-64ece2aed906.png)
This matches the shape of the model from the export.

## The cubes used by the model aren't actually cubes
The Edit Mode image from previous section reveals another problem. Mcblend is quite strict about what is and what isn't a cube. A cube is a mesh which has exactly 8 vertices and 6 faces. The faces should match the bounds of the object (you can enable bounds in _object properties->viewport display->bounds_). You can see some examples in user mnual in _separate cubes operator_ section https://nusiq.github.io/mcblend/basic_operators/#separate-cubes. This operator could fix some of the problems of some of the meshes of the objects in your project but first you need to merge by distance your vertices and change tris to quads. The operator won't help with planes. The planes in your model should be flatten cubes (just like in Minecraft). Unfortunately Mcblend does a bad job at dealing with planes and I'm planning to adress that problem in the future.

**Comment by sekretboi** [comment]
Hello, Ok so.. I realize I have been doing this completely wrong and should've read through the documentation fully. The model was originally made as a full mesh so I had to split the loose parts and join them into cubes. Then I deleted the armature and bones and re-added them after I exported the cubes which was an extremely complicated process because I then had to add the bones into Blockbench. I am going to restart this process and use the stuff you showed me. Thank you a lot bro, this has been some great help
